export const ApiPath = {
  Auth: {
    LOGIN: "/auth/login",
    REFRESH: "/auth/refresh",
    ME: "/auth/me",
  },
  Members: {
    BASE: "/members",
    ALL: "/members/all",
    SEARCH: "/members/search",
    BULK: "/members/bulk",
    EXPORT: "/members/export",
    ONE: (id: string) => `/members/${id}` as const,
  },
  Meters: {
    BASE: "/meters",
    MAP: "/meters/map",
    BY_MEMBER: (memberId: string) => `/meters/member/${memberId}` as const,
    ONE: (id: string) => `/meters/${id}` as const,
    SHARE_PAYMENTS: (id: string) => `/meters/${id}/share-payments` as const,
    SHARE_SUMMARY: (id: string) => `/meters/${id}/share-payments/summary` as const,
  },
  Consumption: {
    BASE: "/consumption",
    BY_METER: (meterId: string) => `/consumption/meter/${meterId}` as const,
    ONE: (id: string) => `/consumption/${id}` as const,
  },
  Billing: {
    BASE: "/billing",
    ONE: (id: string) => `/billing/${id}` as const,
    PAY: (id: string) => `/billing/${id}/pay` as const,
    RECEIPT: (id: string) => `/billing/${id}/receipt` as const,
    RECEIPT_VIEW: (id: string) => `/billing/${id}/receipt/view` as const,
    DISCOUNTS: "/billing/discounts",
    DISCOUNT_ONE: (id: string) => `/billing/discounts/${id}` as const,
    DISCOUNTS_ACTIVE: "/billing/discounts/active",
    GENERATE: (id: string) => `/billing/${id}/generate` as const,
  },
  Tariffs: {
    BASE: "/tariffs",
    ONE: (id: string) => `/tariffs/${id}` as const,
    COPY: "/tariffs/copy",
    BASE_TARIFFS: "/base-tariffs",
    BASE_TARIFFS_ACTIVE: "/base-tariffs/active",
    BASE_TARIFFS_ONE: (id: string) => `/base-tariffs/${id}` as const,
  },
  Shares: {
    BASE: "/shares",
    ACTIVE: "/shares/active",
    ONE: (id: string) => `/shares/${id}` as const,
  },
  Notifications: {
    BASE: "/notifications",
    UNREAD_COUNT: "/notifications/unread-count",
    READ: (id: string) => `/notifications/${id}/read` as const,
    MARK_ALL: "/notifications/mark-all",
  },
  Reports: {
    BASE: "/reports",
    DASHBOARD: "/reports/dashboard",
    REVENUE: "/reports/revenue",
    OVERDUE: "/reports/overdue",
    EXPORT: "/reports/export",
  },
  Users: {
    BASE: "/users",
    ONE: (id: string) => `/users/${id}` as const,
    TOGGLE_ACTIVE: (id: string) => `/users/${id}/toggle-active` as const,
  },
  Roles: {
    BASE: "/roles",
    ONE: (id: string) => `/roles/${id}` as const,
    PERMISSIONS: "/roles/permissions/all",
    ASSIGN_USER_ROLES: (userId: string) => `/roles/users/${userId}/roles` as const,
  },
  Settings: {
    BASE: "/settings",
  },
  Zones: {
    BASE: "/zones",
    ONE: (id: string) => `/zones/${id}` as const,
  },
  ZoneTypes: {
    BASE: "/zone-types",
    ONE: (id: string) => `/zone-types/${id}` as const,
  },
  MeterTypes: {
    BASE: "/meter-types",
    ONE: (id: string) => `/meter-types/${id}` as const,
  },
  Assets: {
    BASE: "/assets",
    BULK: "/assets/bulk",
    SELECT: "/assets/select",
    STATUS_SUMMARY: "/assets/status-summary",
    ONE: (id: string) => `/assets/${id}` as const,
    QR: (id: string) => `/assets/${id}/qr` as const,
    MOVEMENTS: (id: string) => `/assets/${id}/movements` as const,
    MAINTENANCES: (id: string) => `/assets/${id}/maintenances` as const,
    DOCUMENTS: (id: string) => `/assets/${id}/documents` as const,
    PUBLIC: (code: string) => `/assets/public/${code}` as const,
    LOAN: (id: string) => `/assets/${id}/loan` as const,
    RETURN: (id: string) => `/assets/${id}/return` as const,
    TRANSFER: (id: string) => `/assets/${id}/transfer` as const,
    LOST: (id: string) => `/assets/${id}/lost` as const,
    RETIRE: (id: string) => `/assets/${id}/retire` as const,
    RESTORE: (id: string) => `/assets/${id}/restore` as const,
    START_MAINTENANCE: (id: string) => `/assets/${id}/maintenance` as const,
    FINISH_MAINTENANCE: (id: string, maintenanceId: string) =>
      `/assets/${id}/maintenance/${maintenanceId}/finish` as const,
    DOCUMENT: (id: string, documentId: string) =>
      `/assets/${id}/documents/${documentId}` as const,
    DOCUMENT_CONTENT: (id: string, documentId: string) =>
      `/assets/${id}/documents/${documentId}/content` as const,
  },
  AssetCategories: {
    BASE: "/asset-categories",
    ONE: (id: string) => `/asset-categories/${id}` as const,
  },
  AssetLocations: {
    BASE: "/asset-locations",
    ONE: (id: string) => `/asset-locations/${id}` as const,
  },
  Finances: {
    BASE: "/finances",
    ONE: (id: string) => `/finances/${id}` as const,
    VOID: (id: string) => `/finances/${id}/void` as const,
    REPORTS_SUMMARY: "/finances/reports/summary",
    REPORTS_BY_CATEGORY: "/finances/reports/by-category",
    REPORTS_BY_METHOD: "/finances/reports/by-method",
    REPORTS_MONTHLY: "/finances/reports/monthly",
    REPORTS_WATER: "/finances/reports/water",
    REPORTS_EXPORT: "/finances/reports/export",
    DOCUMENTS: (id: string) => `/finances/${id}/documents` as const,
    DOCUMENT: (id: string, documentId: string) =>
      `/finances/${id}/documents/${documentId}` as const,
    DOCUMENT_CONTENT: (id: string, documentId: string) =>
      `/finances/${id}/documents/${documentId}/content` as const,
  },
  FinanceCategories: {
    BASE: "/finance-categories",
    ONE: (id: string) => `/finance-categories/${id}` as const,
  },
  Audit: {
    BASE: "/audit",
    EXPORT: "/audit/export",
  },
  Activities: {
    BASE: "/activities",
    ALL: "/activities/all",
    ONE: (id: string) => `/activities/${id}` as const,
    ATTENDANCE: (id: string) => `/activities/${id}/attendance` as const,
    INITIAL_CONTROL: (id: string) => `/activities/${id}/attendance/initial-control` as const,
    FINAL_CONTROL: (id: string) => `/activities/${id}/attendance/final-control` as const,
    SHARES: (id: string) => `/activities/${id}/shares` as const,
    SHARE_ONE: (activityId: string, userId: string) => `/activities/${activityId}/share/${userId}` as const,
  },
  FineTypes: {
    BASE: "/fine-types",
    ONE: (id: string) => `/fine-types/${id}` as const,
  },
  Attendance: {
    ALL: "/activities/attendance",
    MEMBER_SUMMARY: (memberId: string, activityId: string) =>
      `/activities/attendance/member/${memberId}/summary/${activityId}` as const,
  },
  Fines: {
    BASE: "/fines",
    STATS: "/fines/stats",
    REPORT: "/fines/report",
    MEMBER: (id: string) => `/fines/member/${id}` as const,
    ONE: (id: string) => `/fines/${id}` as const,
    PAY: (id: string) => `/fines/${id}/pay` as const,
    CANCEL: (id: string) => `/fines/${id}/cancel` as const,
    BULK_PAY: "/fines/bulk-pay",
  },
} as const
