export const ApiPath = {
  Auth: {
    LOGIN: "/auth/login",
    REFRESH: "/auth/refresh",
    ME: "/auth/me",
  },
  Members: {
    BASE: "/members",
    ALL: "/members/all",
    SEARCH: "/members/search",
    BULK: "/members/bulk",
    EXPORT: "/members/export",
    ONE: (id: string) => `/members/${id}` as const,
  },
  Meters: {
    BASE: "/meters",
    MAP: "/meters/map",
    BY_MEMBER: (memberId: string) => `/meters/member/${memberId}` as const,
    ONE: (id: string) => `/meters/${id}` as const,
    SHARE_PAYMENTS: (id: string) => `/meters/${id}/share-payments` as const,
    SHARE_SUMMARY: (id: string) => `/meters/${id}/share-payments/summary` as const,
  },
  Consumption: {
    BASE: "/consumption",
    BY_METER: (meterId: string) => `/consumption/meter/${meterId}` as const,
    ONE: (id: string) => `/consumption/${id}` as const,
  },
  Billing: {
    BASE: "/billing",
    ONE: (id: string) => `/billing/${id}` as const,
    PAY: (id: string) => `/billing/${id}/pay` as const,
    RECEIPT: (id: string) => `/billing/${id}/receipt` as const,
    RECEIPT_VIEW: (id: string) => `/billing/${id}/receipt/view` as const,
    DISCOUNTS: "/billing/discounts",
    DISCOUNT_ONE: (id: string) => `/billing/discounts/${id}` as const,
    DISCOUNTS_ACTIVE: "/billing/discounts/active",
    GENERATE: (id: string) => `/billing/${id}/generate` as const,
  },
  Tariffs: {
    BASE: "/tariffs",
    ONE: (id: string) => `/tariffs/${id}` as const,
    COPY: "/tariffs/copy",
    BASE_TARIFFS: "/base-tariffs",
    BASE_TARIFFS_ACTIVE: "/base-tariffs/active",
    BASE_TARIFFS_ONE: (id: string) => `/base-tariffs/${id}` as const,
  },
  Shares: {
    BASE: "/shares",
    ACTIVE: "/shares/active",
    ONE: (id: string) => `/shares/${id}` as const,
  },
  Notifications: {
    BASE: "/notifications",
    UNREAD_COUNT: "/notifications/unread-count",
    READ: (id: string) => `/notifications/${id}/read` as const,
    MARK_ALL: "/notifications/mark-all",
  },
  Reports: {
    BASE: "/reports",
    DASHBOARD: "/reports/dashboard",
    REVENUE: "/reports/revenue",
    OVERDUE: "/reports/overdue",
    EXPORT: "/reports/export",
  },
  Users: {
    BASE: "/users",
    ONE: (id: string) => `/users/${id}` as const,
    TOGGLE_ACTIVE: (id: string) => `/users/${id}/toggle-active` as const,
  },
  Roles: {
    BASE: "/roles",
    ONE: (id: string) => `/roles/${id}` as const,
    PERMISSIONS: "/roles/permissions/all",
    ASSIGN_USER_ROLES: (userId: string) => `/roles/users/${userId}/roles` as const,
  },
  Settings: {
    BASE: "/settings",
  },
  Zones: {
    BASE: "/zones",
    ONE: (id: string) => `/zones/${id}` as const,
  },
  ZoneTypes: {
    BASE: "/zone-types",
    ONE: (id: string) => `/zone-types/${id}` as const,
  },
  MeterTypes: {
    BASE: "/meter-types",
    ONE: (id: string) => `/meter-types/${id}` as const,
  },
  Audit: {
    BASE: "/audit",
    EXPORT: "/audit/export",
  },
  Activities: {
    BASE: "/activities",
    ALL: "/activities/all",
    ONE: (id: string) => `/activities/${id}` as const,
    ATTENDANCE: (id: string) => `/activities/${id}/attendance` as const,
    INITIAL_CONTROL: (id: string) => `/activities/${id}/attendance/initial-control` as const,
    FINAL_CONTROL: (id: string) => `/activities/${id}/attendance/final-control` as const,
    SHARES: (id: string) => `/activities/${id}/shares` as const,
    SHARE_ONE: (activityId: string, userId: string) => `/activities/${activityId}/share/${userId}` as const,
  },
  FineTypes: {
    BASE: "/fine-types",
    ONE: (id: string) => `/fine-types/${id}` as const,
  },
  Attendance: {
    ALL: "/activities/attendance",
    MEMBER_SUMMARY: (memberId: string, activityId: string) =>
      `/activities/attendance/member/${memberId}/summary/${activityId}` as const,
  },
  Fines: {
    BASE: "/fines",
    STATS: "/fines/stats",
    REPORT: "/fines/report",
    MEMBER: (id: string) => `/fines/member/${id}` as const,
    ONE: (id: string) => `/fines/${id}` as const,
    PAY: (id: string) => `/fines/${id}/pay` as const,
    CANCEL: (id: string) => `/fines/${id}/cancel` as const,
    BULK_PAY: "/fines/bulk-pay",
  },
} as const
