import { PartialType } from '@nestjs/swagger';
import { Type } from 'class-transformer';
import {
  IsDateString,
  IsEnum,
  IsInt,
  IsNotEmpty,
  IsNumber,
  IsOptional,
  IsString,
  IsUUID,
  Max,
  Min,
} from 'class-validator';
import { AssetAcquisitionType, AssetCondition } from '../entities/asset.entity';

/**
 * `status` and `code` are intentionally absent: the code is generated by the
 * server and the status only changes through the dedicated action endpoints.
 */
export class CreateAssetDto {
  @IsString()
  @IsNotEmpty()
  name: string;

  @IsOptional()
  @IsString()
  description?: string;

  @IsOptional()
  @IsUUID()
  categoryId?: string;

  @IsOptional()
  @IsUUID()
  locationId?: string;

  @IsOptional()
  @IsEnum(AssetCondition)
  condition?: AssetCondition;

  @IsOptional()
  @Type(() => Number)
  @IsInt()
  @Min(1)
  @Max(1000)
  quantity?: number;

  @IsOptional()
  @IsDateString()
  acquisitionDate?: string;

  @IsOptional()
  @Type(() => Number)
  @IsNumber({ maxDecimalPlaces: 2 })
  @Min(0)
  acquisitionValue?: number;

  @IsOptional()
  @IsEnum(AssetAcquisitionType)
  acquisitionType?: AssetAcquisitionType;

  @IsOptional()
  @IsUUID()
  currentResponsibleUserId?: string;

  @IsOptional()
  @IsUUID()
  currentResponsibleMemberId?: string;

  @IsOptional()
  @IsString()
  notes?: string;
}

export class UpdateAssetDto extends PartialType(CreateAssetDto) {}

/**
 * Creates N individual assets sharing the same descriptive data, each one with
 * its own sequential code. Used for homogeneous lots (e.g. 10 plastic chairs).
 */
export class CreateAssetsBulkDto {
  @IsString()
  @IsNotEmpty()
  name: string;

  @IsOptional()
  @IsString()
  description?: string;

  @IsOptional()
  @IsUUID()
  categoryId?: string;

  @IsOptional()
  @IsUUID()
  locationId?: string;

  @IsOptional()
  @IsEnum(AssetCondition)
  condition?: AssetCondition;

  @Type(() => Number)
  @IsInt()
  @Min(1)
  @Max(500)
  count: number;

  @IsOptional()
  @IsDateString()
  acquisitionDate?: string;

  @IsOptional()
  @Type(() => Number)
  @IsNumber({ maxDecimalPlaces: 2 })
  @Min(0)
  acquisitionValue?: number;

  @IsOptional()
  @IsEnum(AssetAcquisitionType)
  acquisitionType?: AssetAcquisitionType;

  @IsOptional()
  @IsString()
  notes?: string;
}

export class RetireAssetDto {
  @IsDateString()
  retiredAt: string;

  @IsString()
  @IsNotEmpty()
  reason: string;

  @IsOptional()
  @IsUUID()
  responsibleUserId?: string;

  @IsOptional()
  @IsString()
  notes?: string;
}

export class RestoreAssetDto {
  @IsOptional()
  @IsString()
  notes?: string;
}

export class ReportLostAssetDto {
  @IsOptional()
  @IsString()
  reason?: string;
}
