import {
  ArrayNotEmpty,
  IsArray,
  IsOptional,
  IsString,
  IsUUID,
} from 'class-validator';

export class PayFineDto {
  @IsOptional()
  @IsString()
  notes?: string;

  /**
   * User that physically collected the fine. Optional: when omitted the
   * authenticated registrant is assumed to be the collector. The financial
   * responsible always comes from the fine's activity, never from here.
   */
  @IsOptional()
  @IsUUID()
  collectorUserId?: string;
}

export class CancelFineDto {
  @IsOptional()
  @IsString()
  reason?: string;
}

/**
 * Manual fine issued by a user (not generated by the attendance evaluation).
 * `createdByUserId` is never accepted from the client: it is taken from the
 * authenticated user.
 */
export class CreateManualFineDto {
  @IsUUID('4')
  memberId: string;

  @IsUUID('4')
  fineTypeId: string;

  @IsOptional()
  @IsString()
  amount?: string;

  @IsOptional()
  @IsString()
  notes?: string;
}

export class BulkPayFinesDto {
  @IsArray()
  @ArrayNotEmpty()
  @IsUUID('4', { each: true })
  ids: string[];

  @IsOptional()
  @IsString()
  notes?: string;

  /** See PayFineDto.collectorUserId (applied per fine movement). */
  @IsOptional()
  @IsUUID()
  collectorUserId?: string;
}
